server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fto
    username: fto
    password: fto
  jpa:
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    com.fto: DEBUG
